### ISSUE TITLE
I cannot import napari-bbox. 

### ISSUE THREAD

**Issue by cauliflower0077** [bauerdavid/napari-bbox#10]
I encountered an issue while trying to import the napari-bbox plugin. 

It seems like I was importing it from the private napari._qt, and it only works with older versions of napari.

![スクリーンショット (26)](https://github.com/bauerdavid/napari-bbox/assets/154745037/8b2d3e38-871e-465d-b19d-924dde7d5e3f)
![スクリーンショット (27)](https://github.com/bauerdavid/napari-bbox/assets/154745037/104fb8e1-bb92-414a-b7ef-401eebe14e55)
![スクリーンショット (28)](https://github.com/bauerdavid/napari-bbox/assets/154745037/785e5ff7-7a86-48cb-ab9d-497b01c9a90d)
![スクリーンショット (30)](https://github.com/bauerdavid/napari-bbox/assets/154745037/a812c131-73aa-4bda-ad35-a2568501bb1d)

 I want to use this plugin for masking with fill between slices to create 3D annotations(napari-nd- annotator).

**Comment by bauerdavid** [comment]
Hey @cauliflower0077,
unfortunately the plugin is not yet available for `napari==0.4.19`. I was notified about the problem, but I didn't have enough time to inspect the problem, but what's sure is that the plugin has to be reworked for the new napari version. But I will fix it as soon as I get there. Until that, could you use a previous napari version?

**Comment by cauliflower0077** [comment]
Thank you for your reply. I understand.

**Comment by bauerdavid** [comment]
Hey,
I recently published the new version of napari-bbox (0.0.7), which should work with all newer versions of napari (up to 0.4.19). Feel free to try it, and reach out, if you encounter any problems.

**Comment by cauliflower0077** [comment]
I tried it again and succeeded in importing napari-bbox plugin and annotating using it. Thank you.
