### ISSUE TITLE
Bounding boxes not displaying at correct z-heights

### ISSUE THREAD

**Issue by grahamross123** [bauerdavid/napari-bbox#18]
**Describe the bug**
When using a z scale factor in Napari, the bounding boxes do not display at the correct z slices.
e.g. if a bounding box ranges from `z1=0.3` to `z2=1.3`, it will display when the viewer is in the ranges `z1=0.5` to `z2=1.5`. 

**Expected behavior**
Bounding boxes should display at the correct z slices regardless of the scaling factor used.

**Comment by grahamross123** [comment]
Hi @bauerdavid,

I've experienced another minor issue. This can be fixed by keeping the bounding box slice key as a float instead of an integer [here](https://github.com/bauerdavid/napari-bbox/blob/main/src/napari_bbox/boundingbox/napari_0_4_18/bounding_box.py#L183) as the slices can include decimals when a scaling factor is used. If this is desired, I can submit the pull request.

Thanks,
Graham

**Comment by bauerdavid** [comment]
Hey @grahamross123,
please do so! I just created a new release, but I will include it in the next one
Thanks!

**Comment by psobolewskiPhD** [comment]
I've also run into this, so gentle bump @bauerdavid ❤️
