### ISSUE TITLE
Genrally broken with napari 0.4.18

### ISSUE THREAD

**Issue by Chris-N-K** [bauerdavid/napari-bbox#7]
**Describe the bug**
This plugin does no longer work with napari 0.4.18 due to some API changes on napari side.

See issue #6, plus the _finish_drawing() machinery of the `BoundingBoxLayer` gets called during ´_init_´ before the relevant attributes of `BoundingBoxLayer` are created causing errors. 

**To Reproduce**
1. Install with napari 0.4.18
2. Try to use the plugin

**Comment by Chris-N-K** [comment]
One part of the problem seems to be the removal of _ndisplay
-> `Remove layer ndisplay event` [#5491](https://github.com/napari/napari/pull/5491)

**Comment by bauerdavid** [comment]
Hey @Chris-N-K ,
thanks for the report! The plugin was not yet tested with the newest version of napari. Unfortunately I'm quite busy nowadays, but I'll try to correct is asap.

**Comment by bauerdavid** [comment]
Hey,
I recently published the new version of napari-bbox (0.0.7), which should work with all newer versions of napari (up to 0.4.19). Feel free to try it, and reach out, if you encounter any problems.
